staging_project_id = "staging-adk"
prod_project_id = "production-adk"
cicd_runner_project_id = "production-adk"
region = "us-central1"
repository_name = "my-agentic-rag"
repository_owner = "Michaelktker"
host_connection_name = "git-my-agentic-rag"
create_cb_connection = true
create_repository = false
github_app_installation_id = "54681073"
github_pat_secret_id = "git-my-agentic-rag-github-oauthtoken-ddff64"
# fal_api_key = "your-fal-api-key-here"  # Uncomment and set during deployment
