# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "python:3.11-slim"
    id: deploy-data-ingestion-pipeline-prod
    entrypoint: bash
    args:
      - -c
      - |
        cd data_ingestion && pip install uv==0.6.12 --user && cd data_ingestion_pipeline && \
        uv sync --locked && uv run python submit_pipeline.py
    env:
      - "PIPELINE_ROOT=${_PIPELINE_GCS_ROOT_PROD}"
      - "REGION=${_REGION}"
      - "DATA_STORE_REGION=${_DATA_STORE_REGION}"
      - "DATA_STORE_ID=${_DATA_STORE_ID_PROD}"
      - "PROJECT_ID=${_PROD_PROJECT_ID}"
      - "SERVICE_ACCOUNT=${_PIPELINE_SA_EMAIL_PROD}"
      - "PIPELINE_NAME=${_PIPELINE_NAME}"
      - "CRON_SCHEDULE=${_PIPELINE_CRON_SCHEDULE}"
      - "DISABLE_CACHING=TRUE"
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'
   
  - name: "gcr.io/cloud-builders/gcloud"
    id: trigger-deployment
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "my-agentic-rag"
      - "--image"
      - "us-central1-docker.pkg.dev/staging-adk/my-agentic-rag-docker-repo/my-agentic-rag:latest"
      - "--region"
      - "$_REGION"
      - "--project"
      - $_PROD_PROJECT_ID

substitutions:
  _PROD_PROJECT_ID: production-adk
  _REGION: us-central1
  _DATA_STORE_REGION: us
  _DATA_STORE_ID_PROD: my-agentic-rag-datastore-prod
  _PIPELINE_GCS_ROOT_PROD: gs://production-adk-my-agentic-rag-rag
  _PIPELINE_SA_EMAIL_PROD: my-agentic-rag-rag@production-adk.iam.gserviceaccount.com
  _PIPELINE_NAME: data-ingestion-pipeline
  _PIPELINE_CRON_SCHEDULE: ""
  _ARTIFACT_REGISTRY_REPO_NAME: my-agentic-rag-docker-repo
  _CONTAINER_NAME: my-agentic-rag

logsBucket: gs://${PROJECT_ID}-my-agentic-rag-logs-data/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
